/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class LoadingUI extends Scene {
		public tips:Laya.Text;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Loading");
        }
    }
    REG("ui.LoadingUI",LoadingUI);
    export class RockerUI extends View {
		public joystickBg:Laya.Image;
		public joystickPoint:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Rocker");
        }
    }
    REG("ui.RockerUI",RockerUI);
    export class UIMainUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("UIMain");
        }
    }
    REG("ui.UIMainUI",UIMainUI);
    export class VideoUI extends Scene {
		public btn_close:Laya.Image;
		public videoWin:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Video");
        }
    }
    REG("ui.VideoUI",VideoUI);
}